### ISSUE TITLE
Question about Exposure fusion

### ISSUE THREAD

**Issue by emi0116** [sujiwo/im_enhance#2]
I think Exposure fusion is a method to combine the same scene with different exposure parameters, but your method uses only one image. Why is this?

**Comment by sujiwo** [comment]
Hi, and thanks for your interest in my program!

The name `exposure fusion' actually came from original paper by Ying et al "A New Image Contrast Enhancement Algorithm
using Exposure Fusion Framework", which explain that this method actually fuses original image and its synthetic version at which underexposed areas have been brightened.

That's why this method is unable to handle over-exposed images (also to answer your first question).

**Comment by emi0116** [comment]
Thanks for the quick answer!
